### ISSUE TITLE
Authentication crashes..

### ISSUE THREAD

**Issue by Br3nda** [jcasoft/GoogleCalendarSkill#5]
After successfully authenticating in the browser, this happens:

```
Authentication successful.
Storing credentials to /home/brenda/.credentials
Your Google Calendar Skill is now authenticated 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/brenda/.mycroft/skills/GoogleCalendarSkill/__main__.py", line 87, in <module>
    start = datetime.datetime.strptime(start,"%Y-%m-%dT%H:%M:%S-%f")
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2017-09-30' does not match format '%Y-%m-%dT%H:%M:%S-%f'
```

**Comment by jcasoft** [comment]
GoogleCalendarSkill is available to be installed by MSM and with manual method for Mark1

**Comment by Br3nda** [comment]
ah, thanks @jcasoft  - yes i installed with MSM.

But that doesn't seem to have anything to do with why the python code is parsing for '%Y-%m-%dT%H:%M:%S-%f' while Google returns %Y-%m-%d

Can you explain?

**Comment by Br3nda** [comment]
Did you comment on the wrong thing @jcasoft  ? You comment would make a lot more sense if it was on  #4

**Comment by jcasoft** [comment]
This problem has been fixed, try again with the authorization process:

cd  /opt/mycroft/skills
workon mycroft
python GoogleCalendarSkill

**Comment by jcasoft** [comment]
Fixed !
