### ISSUE TITLE
NameError: name 'get_localzone' is not defined

### ISSUE THREAD

**Issue by TheCranston** [jcasoft/GoogleCalendarSkill#7]
After following the guide on a picroft, and a manual invocation of the skill I receive the following:

mycroft@picroft:/opt/mycroft/skills$ python GoogleCalendarSkill
checking for cached credentials
Loaded credentials for Google Calendar Skill from /home/mycroft/.credentials
-->RAKE AND RUN   Pick up at 5 at School at 3:00 PM
-->Parent conferences.  at 4:00 PM
-->cardo drum?? at 6:30 PM
-->Reading at 8:00 PM
-->New Event at 5:30 PM
-->farm day. 8:30 am.  at 8:30 AM
-->at farm by 9am at 9:00 AM
-->Farm Distribution at 12:00 PM
-->mow yard at 12:45 PM
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/mycroft/skills/GoogleCalendarSkill/__main__.py", line 88, in <module>
    start =  dateutil.parser.parse(start + " 00:00:00 LOC", tzinfos={"LOC": get_localzone()})
NameError: name 'get_localzone' is not defined
mycroft@picroft:/opt/mycroft/skills$

**Comment by jcasoft** [comment]
The problem has already been corrected, you can do "git pull" and try again.
or add "from tzlocal import get_localzone" at the begining of  __main__.py

**Comment by jcasoft** [comment]
Fixed !
